#!/bin/bash
#update raspberry pi
sudo apt-get clean
sudo apt-get autoremove -y
sudo apt-get update
sudo apt full-upgrade
sudo apt dist-upgrade
sudo apt-get install xboxdrv
sudo pip3 install adafruit-pca9685
echo "Pi is up to date"
